class DailyQuote {
  final String text;
  final String author;
  const DailyQuote(this.text, this.author);
}

class DailyQuotes {
  DailyQuotes._();

  static DailyQuote forToday() {
    final now = DateTime.now();
    final dayOfYear = now.difference(DateTime(now.year)).inDays;
    return _quotes[dayOfYear % _quotes.length];
  }

  static const List<DailyQuote> _quotes = [
    DailyQuote('Nuk ka pasuri më të madhe se intelekti dhe mendja, dhe nuk ka varfëri më të madhe se injoranca.', 'Ali ibn Abi Talib'),
    DailyQuote('Kush kërkon dije për hir të kësaj bote, dija nuk do të zërë rrënjë në zemrën e tij.', 'Imam Ebu Hanife'),
    DailyQuote('Kush kërkon dituri pa vepruar sipas saj, është si ai që mbledh dru në pyll natën: nuk e di se çfarë po merr në dorë.', 'Imam El Gazali'),
    DailyQuote('Mendjemadhësia dhe vetëpëlqimi janë sëmundje shkatërruese që e zhvlerësojnë krejtësisht diturinë e një njeriu.', 'Hasan el Basri'),
    DailyQuote('Nëse dëshiron të përfitosh nga Kurani, përqendrohu kur e lexon apo kur e dëgjon, dhe sill ndërmend se Ai që po të flet është vetë Krijuesi yt.', 'Ibn Kajjimi'),
    DailyQuote('Dynjaja është e tërë kalimtare, ndërsa veprat e mira janë kapitali i vetëm që do të mbetet me ne pas vdekjes.', 'Ibn Kethiri'),
    DailyQuote('Dituria nuk qëndron në transmetimet e shumta, por qëndron në frikën dhe respektin ndaj Allahut në fshehtësi dhe në publik.', 'Ibn Rexhebi'),
    DailyQuote('Kush kërkon dituri me qëllim që të debatojë dhe të tregohet superior ndaj të tjerëve, ka humbur bereqetin e saj.', 'Ibn Tejmijje'),
    DailyQuote('Shkruaji mendimet e tua sapo të të vijnë në mendje, sepse ato janë si gjahu i egër — nëse nuk e lidh me shkrim, ikën dhe nuk kthehet më.', 'Ibn Xhewzi'),
    DailyQuote('Njerëzit kanë nevojë për dituri dhe urtësi më shumë sesa kanë nevojë për ushqim dhe pije; sepse ushqimi u duhet një ose dy herë në ditë, ndërsa dituria u duhet në çdo frymëmarrje.', 'Imam Ahmedi'),
    DailyQuote('Dija është para fjalës dhe veprës.', 'Imam Buhariu'),
    DailyQuote('Mësoje edebin (sjelljen e mirë) përpara se të mësosh diturinë.', 'Imam Maliku'),
    DailyQuote('Dija nuk është ajo që mësohet përmendësh, por dija është ajo që sjell dobi.', 'Imam Shafiu'),
    DailyQuote('Nëse sheh një lexues të Kuranit që shkon shpesh te dyert e sundimtarëve, dije se ai është vjedhës.', 'Sufjan eth-Theuri'),
    DailyQuote('Dy njerëz nuk do të ngopen kurrë: kërkuesi i diturisë dhe kërkuesi i kësaj bote.', 'Ali ibn Abi Talib'),
    DailyQuote('Kur njerëzit të lavdërojnë për atë që mendojnë se ke, kthehu te vetja dhe shih atë që e di me siguri se ke.', 'Ibn Ata\'ilah'),
    DailyQuote('Dija pa veprim është si një trup pa shpirt.', 'Imam Ebu Hanife'),
    DailyQuote('Nëse e sheh veten duke u gëzuar për shkak të lavdërimeve të njerëzve, dije se je në rrezik të madh.', 'Fudejl ibn Ijad'),
    DailyQuote('Të folurit e pakët dhe meditimi i gjatë janë çelësat që hapin dyert e urtësisë në shpirtin e besimtarit.', 'Imam El Gazali'),
    DailyQuote('Mësoni diturinë dhe shoqërojeni atë me qetësi dhe butësi ndaj të tjerëve.', 'Hasan el Basri'),
    DailyQuote('Shenja e lumturisë së një njeriu është që sa më shumë që i shtohet dituria, aq më shumë i shtohet përulësia.', 'Ibn Kajjimi'),
    DailyQuote('Kush e pastron qëllimin e tij vetëm për Allahun, Allahu do t\'i dhurojë atij dritë në zemër dhe sukses në çdo punë.', 'Ibn Rexhebi'),
    DailyQuote('Shoqëria me njerëz të mirë dhe të ditur të ndihmon të qëndrosh i palëkundur në fe gjatë kohërave të vështira.', 'Ibn Tejmijje'),
    DailyQuote('Dritarja e mendjes duhet të jetë gjithmonë e hapur ndaj diturisë. Ai që thotë "kam mësuar mjaftueshëm" ka filluar rënien e tij shpirtërore.', 'Ibn Xhewzi'),
    DailyQuote('Mësoni diturinë me përulësi, sepse ai që krenohet me diturinë e tij ka filluar të bjerë në injorancë.', 'Imam Ahmedi'),
    DailyQuote('Vepra më e dashur tek Allahu është ajo që vazhdon rregullisht, edhe nëse është e pakët.', 'Imam Buhariu'),
    DailyQuote('Dituria nuk shtohet me transmetime të shumta, por dituria është një dritë që Allahu e hedh në zemrën e robit të Tij.', 'Imam Maliku'),
    DailyQuote('Kush dëshiron ta fitojë dynjanë, le t\'i rreket dijes, dhe kush dëshiron ta fitojë ahiretin, le t\'i rreket dijes po kështu.', 'Imam Shafiu'),
    DailyQuote('Kërkohet dituria që me të të kihet frikë Allahu.', 'Sufjan eth-Theuri'),
    DailyQuote('Dituria të ruan ty nga e keqja, ndërsa pasurinë duhet ta ruash ti me mund.', 'Ali ibn Abi Talib'),
    DailyQuote('Nuk ka varfëri më të madhe se injoranca, dhe nuk ka pasuri më të madhe se urtësia e dhuruar nga Zoti.', 'Ibn Ata\'ilah'),
    DailyQuote('Kush flet për fe pa pasur dituri, e humb veten dhe i çon të tjerët në humbje.', 'Imam Ebu Hanife'),
    DailyQuote('Dija pa punë është argument kundër teje, ndërsa puna pa dituri është humbje.', 'Fudejl ibn Ijad'),
    DailyQuote('Dobia e vërtetë e diturisë shfaqet në përulësinë dhe sjelljen e mirë të njeriut, jo në numrin e debateve që fiton.', 'Imam El Gazali'),
    DailyQuote('Kush nuk mund të durojë vështirësinë e kërkimit të diturisë, do të mbetet në poshtërimin e injorancës gjithë jetën.', 'Hasan el Basri'),
    DailyQuote('Nuk ka ndëshkim më të madh për një rob sansa ngurtësimi i zemrës së tij dhe largimi i saj nga Allahu.', 'Ibn Kajjimi'),
    DailyQuote('Dituria e vërtetë është ajo që të shton frikën ndaj Zotit tënd dhe të udhëzon drejt përulësisë dhe respektit.', 'Ibn Kethiri'),
    DailyQuote('Dituria e vërtetë është ajo që të afron me Zotin tënd dhe të largon nga mendjemadhësia.', 'Ibn Rexhebi'),
    DailyQuote('Mendjemadhësia e vdes dritën e intelektit dhe e bën njeriun të shohë gabimet e të tjerëve duke harruar të metat e veta.', 'Ibn Tejmijje'),
    DailyQuote('Dituria pa vepër është si një pemë pa fruta, ose si një armë në duart e atij që nuk di ta përdorë.', 'Ibn Xhewzi'),
    DailyQuote('Të folurit e pakët është zbukurim për të mençurin dhe mbulesë për të paditurin.', 'Imam Ahmedi'),
    DailyQuote('Kushdo që shpenzon kohën në biseda të kota, do t\'i hiqet bereqeti i diturisë dhe i punës.', 'Imam Maliku'),
    DailyQuote('Dija nuk është thjesht transmetim i thënieve, por është frikërespekt ndaj Allahut dhe zbatim i asaj që njeriu ka mësuar.', 'Imam Neueuiu'),
    DailyQuote('Sa më pak dituri që ka njeriu, aq më shumë debaton dhe ngul këmbë në gabimin e tij.', 'Imam Shafiu'),
    DailyQuote('Dija ka nevojë për vepër, përndryshe ajo largohet.', 'Sufjan eth-Theuri'),
    DailyQuote('Mendjemadhësia është pengesë për zhvillimin e mendjes dhe intelektit.', 'Ali ibn Abi Talib'),
    DailyQuote('Kërkimi i dijes është obligim për çdo musliman, sepse pa të njeriu ecën në errësirë.', 'Imam Ebu Hanife'),
    DailyQuote('Kërkimi i diturisë duhet të bëhet për hir të Allahut, e jo për t\'u mburrur para të tjerëve ose për të fituar famë.', 'Fudejl ibn Ijad'),
    DailyQuote('Zemërimi është si një zjarr i ndezur në zemër; ai shkatërron intelektin dhe e bën njeriun të sillet si i marrë.', 'Imam El Gazali'),
    DailyQuote('Kush flet më pak dhe mendon më shumë, ka shpëtuar mendjen e tij; kush flet shumë dhe mendon pak, ka shkatërruar veten.', 'Hasan el Basri'),
    DailyQuote('Dituria pa pasim të rrugës së profetit është vetëm një grumbull informacionesh pa asnjë dobi për shpirtin.', 'Ibn Kethiri'),
    DailyQuote('Nuk e ka shijuar ëmbëlsinë e diturisë ai që nuk ka pasur durim në vështirësitë e kërkimit të saj.', 'Imam Ahmedi'),
    DailyQuote('Nëse sheh një njeri që flet shumë pa nevojë, dije se mendja e tij ka filluar të dobësohet.', 'Imam Maliku'),
    DailyQuote('Kushdo që fsheh dijen që u bën dobi njerëzve, do të ringjallet në Ditën e Gjykimit me një fre prej zjarri në gojën e tij.', 'Imam Neueuiu'),
    DailyQuote('Tre gjëra e shtojnë intelektin: ndeja me dijetarët, ndeja me njerëzit e mirë dhe lënia e fjalëve që nuk të përkasin.', 'Imam Shafiu'),
    DailyQuote('Njeriu më i mençur është ai që i frikësohet më shumë Allahut.', 'Sufjan eth-Theuri'),
    DailyQuote('Syri i të urtit sheh fundin e çdo çështjeje që në hapat e parë të saj.', 'Ali ibn Abi Talib'),
    DailyQuote('Drita e intelektit të tregon krijesat, ndërsa drita e zemrës të tregon se çdo gjë është e varur nga Krijuesi.', 'Ibn Ata\'ilah'),
    DailyQuote('Nuk ka shok më të mirë në këtë jetë sansa një libër i dobishëm që të kujton Zotin tënd dhe të udhëzon drejt moralit të lartë.', 'Imam El Gazali'),
    DailyQuote('Dynjaja është e tërë errësirë, përveç vendeve ku përmendet Allahu dhe ku përhapet dituria.', 'Hasan el Basri'),
    DailyQuote('Dituria pa vepra është si një pemë pa fruta, ndërsa veprat pa sinqeritet janë si një trup pa shpirt.', 'Ibn Kajjimi'),
    DailyQuote('Dynjaja është si një rrugëtim i shkurtër; mos e ngarko veten me gjëra që nuk të nevojiten për rrugën.', 'Ibn Kethiri'),
    DailyQuote('Dituria pa ndershmëri dhe pa përulësi është vetëm një rrugë më e shkurtër drejt humbjes.', 'Ibn Xhewzi'),
    DailyQuote('Dobia e vërtetë e diturisë është përulësia dhe frika ndaj Allahut; nëse shton vetëm debatet, ke humbur qëllimin.', 'Imam Ahmedi'),
    DailyQuote('Kushdo që dëshiron të gjejë urtësinë, le të ulet me pleqtë e devotshëm dhe me dijetarët e sinqertë.', 'Imam Maliku'),
    DailyQuote('Edukimi i shpirtit dhe kërkimi i dijes kërkojnë durim të madh; kush nuk e duron pluhurin e kërkimit të dijes, do të mbetet në injorancë tërë jetën.', 'Imam Neueuiu'),
    DailyQuote('Heshtja e të diturit është përgjigjja më e mirë për të paditurin që kërkon debat.', 'Imam Shafiu'),
    DailyQuote('Nuk ka pasur kohë në të cilën njerëzit kanë pasur më shumë nevojë për dituri sansa kjo kohë e jona.', 'Sufjan eth-Theuri'),
    DailyQuote('Pasuria pa mendje është si një shtëpi pa çati; shembet me stuhinë e parë.', 'Ali ibn Abi Talib'),
    DailyQuote('Dobia më e madhe e diturisë është se ajo të largon nga mendjemadhësia dhe të afron drejt përulësisë.', 'Ibn Ata\'ilah'),
    DailyQuote('Nëse e humb keqardhjen për mëkatet që ke bërë, dije se zemra jote ka filluar të ngurtësohet.', 'Fudejl ibn Ijad'),
    DailyQuote('Nuk ka stoli më të bukur për dijetarin sansa përulësia dhe pranimi i gabimeve të tij pa hezitim.', 'Imam El Gazali'),
    DailyQuote('Vlera e diturisë nuk qëndron në atë se sa di, por në atë se sa frikë dhe respekt ke ndaj Allahut.', 'Hasan el Basri'),
    DailyQuote('Neglizhenca ndaj kërkimit të faljes (istigfarit) është fillimi i ngurtësimit të zemrës.', 'Ibn Rexhebi'),
    DailyQuote('Nuk ka asgjë më të keqe sansa një dijetar i cili e shet diturinë e tij për interesat e kësaj bote.', 'Ibn Xhewzi'),
    DailyQuote('Kush kërkon famë përmes diturisë së tij, do të poshtërohet dhe do të harrohet nga njerëzit.', 'Imam Maliku'),
    DailyQuote('Dijetari i vërtetë është ai që e përdor dijen e tij për të udhëzuar njerëzit me butësi dhe urtësi, e jo për t\'u mburrur para tyre.', 'Imam Neueuiu'),
    DailyQuote('Intelekti i njeriut ndriçohet me lexim të vazhdueshëm të Kuranit dhe kuptim të porosive të tij.', 'Imam Shafiu'),
    DailyQuote('Mos fol për veten tënde me lavdërime, sepse kjo të shpie në vetëpëlqim, i cili shkatërron veprat.', 'Sufjan eth-Theuri'),
    DailyQuote('Intelekti është pasuria më e madhe, ndërsa injoranca është varfëria më e rëndë.', 'Ali ibn Abi Talib'),
    DailyQuote('Lënia e punëve të mira për shkak se njerëzit mund të të shohin është syefaqësi, ndërsa bërja e tyre për t\'u parë prej tyre është shirk.', 'Ibn Ata\'ilah'),
    DailyQuote('Kush kërkon diturinë e fesë pa pasur qëllim të pastër për hir të Allahut, nuk do të gjejë dobi në të dhe do të mbetet i zbrazët.', 'Imam Ebu Hanife'),
    DailyQuote('Nuk ka padituri më të madhe sansa të njohësh të metat e të tjerëve dhe të jesh i verbër ndaj të metave të tua.', 'Imam El Gazali'),
    DailyQuote('Meditojeni Kur\'anin dhe veproni sipas tij; mos u mjaftoni vetëm me leximin e shkronjave pa kuptuar kuptimet e tyre.', 'Hasan el Basri'),
    DailyQuote('Nëse dëshiron të përfitosh nga Kur\'ani, përqendro zemrën tënde kur e lexon apo e dëgjon atë, dëgjo me vëmendje dhe prezantohu sikur Allahu po të drejtohet ty.', 'Ibn Kajjimi'),
    DailyQuote('Historia e popujve të kaluar është një mësim i madh për ata që kanë mendje të shëndoshë dhe kërkojnë të vërtetën.', 'Ibn Kethiri'),
    DailyQuote('Kërkimi i diturisë kërkon durim të gjatë dhe qëllim të pastër; kushdo që nxiton, do të mbetet pa përfituar asgjë.', 'Ibn Rexhebi'),
    DailyQuote('Diturisë nuk i përngjan asgjë (në vlerë), për atë që e ka qëllimin e pastër.', 'Imam Ahmedi'),
    DailyQuote('Kushdo që nuk duron përulësinë e të mësuarit për një orë, do të mbetet në errësirën e injorancës për gjithë jetën.', 'Imam Buhariu'),
    DailyQuote('Injoranca është sëmundje, ndërsa shërimi i saj gjendet në pyetjen e dijetarëve të sinqertë.', 'Imam Maliku'),
    DailyQuote('Kush dëshiron që dija e tij të ketë bereqet, le të jetë i përulur ndaj mësuesve të tij dhe respektues ndaj shokëve të tij.', 'Imam Neueuiu'),
    DailyQuote('Kush kërkon diturinë pa pasur durim, është si ai që kërkon të mbledhë ujë me shportë.', 'Imam Shafiu'),
    DailyQuote('Kush nuk ka moral të mirë, dituria e tij do të jetë argument kundër tij e jo në dobi të tij.', 'Sufjan eth-Theuri'),
    DailyQuote('Vlera e çdo njeriu qëndron në atë që ai bën mirë dhe përsos në punën e tij.', 'Ali ibn Abi Talib'),
    DailyQuote('Mësoni edukatën dhe moralin e mirë përpara se të filloni të mësoni çështjet e detajuara të diturisë.', 'Imam Ebu Hanife'),
    DailyQuote('Dituria pa vepra është marrëzi, ndërsa veprat pa dituri janë devijim dhe humbje.', 'Imam El Gazali'),
    DailyQuote('Dija është të njohurit e të vërtetës me argumentet e saj. Kjo nuk është thjesht transmetim i mendimeve të njerëzve.', 'Ibn Kajjimi'),
    DailyQuote('Kushdo që e lexon Kur\'anin me meditim dhe kuptim, do të gjejë në të përgjigjen për çdo pyetje dhe shërim për çdo sëmundje.', 'Ibn Kethiri'),
    DailyQuote('Dituria pa pasimin e Sunetit është si një pemë pa fruta që nuk sjell asnjë dobi.', 'Ibn Tejmijje'),
    DailyQuote('Heshtja kur nuk ke dituri është shenjë e urtësisë dhe e ruajtjes së fesë.', 'Ibn Xhewzi'),
    DailyQuote('Zemërimi e prish mendjen e shëndoshë; mos merrni vendime kur jeni të zemëruar.', 'Imam Maliku'),
    DailyQuote('Dija e dobishme është ajo që të afron tek Allahu, të bën të njohësh të metat e tua dhe të shton dëshirën për ahiretin.', 'Imam Neueuiu'),
    DailyQuote('Të flasësh pak dhe të punosh shumë është shenjë e besimtarit që kërkon sinqeritetin.', 'Sufjan eth-Theuri'),
    DailyQuote('Nëse sheh se thënia ime bie ndesh me hadithin e saktë të Profetit, atëherë vepro me hadithin dhe hidhe thënien time pas shpine.', 'Imam Shafiu'),
    DailyQuote('Mendja e të urtit qëndron prapa gjuhës së tij, ndërsa gjuha e të paditurit qëndron para mendjes së tij.', 'Ali ibn Abi Talib'),
    DailyQuote('Kushdo që flet për fenë pa pasur dituri të sigurt, po ndërton një rrugë drejt shkatërrimit të vetvetes.', 'Imam Ebu Hanife'),
    DailyQuote('Dija pa moral dhe pa frikë ndaj Allahut është si një pemë e bukur që nuk jep asnjë frut.', 'Fudejl ibn Ijad'),
    DailyQuote('Zemërimi i tepërt e prish mendjen ashtu siç e prish helmi trupin e njeriut.', 'Imam El Gazali'),
    DailyQuote('Ai që e mbjell kohën e tij me dhikër dhe punë të mira, do ta korrë atë me gëzim dhe lumturi të përjetshme.', 'Ibn Kajjimi'),
    DailyQuote('Kërkimi i diturisë është obligim për çdo musliman; ajo ndriçon rrugën tonë në këtë botë dhe në tjetrën.', 'Ibn Kethiri'),
    DailyQuote('Shenja e pranimit të një vepre të mirë është kryerja e një vepre tjetër të mirë pas saj.', 'Ibn Rexhebi'),
    DailyQuote('Dituria e vërtetë të bën të përulur para Krijuesit dhe të butë me krijesat.', 'Ibn Xhewzi'),
    DailyQuote('Me shishen e bojës (kërkimin e diturisë) deri në varr!', 'Imam Ahmedi'),
    DailyQuote('Zilia i ha veprat e mira ashtu siç zjarri i ha drutë.', 'Imam Buhariu'),
    DailyQuote('Urtësia është stoli e pleqërisë dhe dritë për rininë.', 'Imam Maliku'),
    DailyQuote('Dituria nuk është ajo që mësohet përmendësh, por dituria është ajo që sjell dobi në praktikë.', 'Imam Shafiu'),
    DailyQuote('Dituria pa devotshmëri dhe frikë ndaj Allahut është si një pemë e tharë pa asnjë frut.', 'Sufjan eth-Theuri'),
    DailyQuote('Mëkati më i rëndë është ai që bëhet me vetëdije të plotë dhe konsiderohet i vogël nga ai që e bën.', 'Ali ibn Abi Talib'),
    DailyQuote('Kush kërkon diturinë për të marrë famë apo pasuri, ka blerë shkatërrimin e vet me çmimin më të lartë.', 'Imam El Gazali'),
    DailyQuote('Kush nuk ka edukatë, nuk ka dije; kush nuk ka durim, nuk ka fe; dhe kush nuk ka devotshmëri, nuk ka afërsi me Allahun.', 'Hasan el Basri'),
    DailyQuote('Dija pa vepër është si një pemë pa fruta, ndërsa vepra pa sinqeritet është si pluhuri që e merr era.', 'Ibn Kajjimi'),
    DailyQuote('Dituria pa veprim është si një pemë pa fryte; ajo nuk i sjell dobi atij që e zotëron e as të tjerëve.', 'Ibn Rexhebi'),
    DailyQuote('Çdo dituri që nuk e afron njeriun tek Allahu dhe nuk e shtyn atë drejt veprave të mira, është një argument kundër tij në Ditën e Gjykimit.', 'Ibn Tejmijje'),
    DailyQuote('Gjëja më e mirë dhe më e vlefshme është shoqërimi i vazhdueshëm me diturinë dhe të punuarit sipas saj.', 'Ibn Xhewzi'),
    DailyQuote('Dituria është vetëm ajo që shoqërohet me vepra; prandaj ai që nuk punon sipas asaj që di, nuk mund të quhet dijetar.', 'Imam Ahmedi'),
    DailyQuote('Kush kërkon të lartësohet në këtë botë pa pasur dituri dhe moral, është si ai që ndërton një shtëpi mbi rërë.', 'Imam Shafiu'),
    DailyQuote('Frika nga Zoti në vetmi është fillimi i çdo urtësie dhe mbrojtje nga çdo rrezik.', 'Ali ibn Abi Talib'),
    DailyQuote('Dituria pa veprim është marrëzi, ndërsa veprimi pa dituri nuk mund të ekzistojë si i saktë.', 'Imam El Gazali'),
    DailyQuote('Kërkimi i dijës në moshë të re është si gdhendja në gur.', 'Hasan el Basri'),
    DailyQuote('Kushdo që e lexon dhe e mëson përmendësh Kur\'anin, e më pas vepron sipas tij, do të ketë një pozitë të lartë dhe të nderuar në Ditën e Gjykimit.', 'Ibn Kethiri'),
    DailyQuote('Nuk ka udhëzim më të sigurt sansa ai që buron nga Kurani dhe Suneti; kushdo që kërkon udhëzim jashtë tyre, do të humbasë rrugën.', 'Ibn Tejmijje'),
    DailyQuote('Kush dëshiron që veprat e tij të mira të mos ndërpriten pas vdekjes, le të përhapë diturinë.', 'Ibn Xhewzi'),
    DailyQuote('Kush ndjek një rrugë për të kërkuar dituri, Allahu do t\'i lehtësojë atij rrugën për në Xhenet.', 'Imam Buhariu'),
    DailyQuote('Mburoja e dijetarit është shprehja "nuk e di"; nëse ai e braktis atë mburojë, ai e ekspozon veten ndaj shkatërrimit.', 'Imam Maliku'),
    DailyQuote('Nuk kam parë asgjë më të dobishme për trupin dhe mendjen sansa agjërimi i rregullt dhe meditimi i Kur\'anit.', 'Imam Shafiu'),
    DailyQuote('Kush planifikon jetën e tij sikur do të jetojë përgjithmonë, do t\'i shtohen shpresat e rreme dhe do t\'i pakësohen veprat e mira.', 'Sufjan eth-Theuri'),
    DailyQuote('Dituria është dy llojesh: ajo që vetëm dëgjohet dhe ajo që përvetësohet në zemër. Dituria e dëgjuar nuk bën dobi nëse nuk përvetësohet.', 'Ali ibn Abi Talib'),
    DailyQuote('Nëse mëson dituri për një mijë vjet dhe grumbullon një mijë libra, nuk do të jesh i përgatitur për mëshirën e Allahut përveçse përmes veprave të tua.', 'Imam El Gazali'),
    DailyQuote('Një punë e pakët por e kryer me dije, është shumë më e dobishme sansa një punë e madhe e bërë pa dije.', 'Hasan el Basri'),
    DailyQuote('Kur\'ani është burimi i parë i dritës për mendjen dhe udhërrëfyesi i vetëm për shpirtin drejt njohjes së vërtetë të Krijuesit.', 'Ibn Kethiri'),
    DailyQuote('Zbukurimi i mëkatit dhe paraqitja e tij si diçka e mirë është një nga kurthet më të mëdha të Iblisit për të devijuar njerëzit.', 'Ibn Xhewzi'),
    DailyQuote('Kërkimi i diturisë është më i vlefshëm se namazi nafile (vullnetar) për atë që ka qëllim të pastër.', 'Imam Shafiu'),
    DailyQuote('Dallimi mes dijetarit të vërtetë dhe atij të keq është se i vërteti synon botën tjetër me diturinë e tij, ndërsa i keqi kërkon famën dhe pasurinë e kësaj bote.', 'Imam El Gazali'),
    DailyQuote('Kush kërkon diturinë për hir të Allahut, zemra e tij do të zbutet dhe do të mbushet me përulësi ndaj Krijuesit dhe krijesave.', 'Ibn Rexhebi'),
    DailyQuote('Dituria dhe punët e mira janë si binjakë, ndërsa nëna e tyre është vullneti i lartë.', 'Ibn Xhewzi'),
    DailyQuote('Kur u pyet se deri kur duhet të shkruajë e të kërkojë njeriu hadithet, ai u përgjigj: "Deri sa të vdesë".', 'Imam Ahmedi'),
    DailyQuote('Kush dëshiron që zemra e tij të hapet dhe të ndriçohet me dituri, le të ketë më pak fjalë dhe të veprojë më shumë në fshehtësi.', 'Imam Maliku'),
    DailyQuote('Dituria është më e mirë se pasuria; dituria të ruan ty, ndërsa pasurinë duhet ta ruash ti.', 'Ali ibn Abi Talib'),
    DailyQuote('Nëse dituria nuk të dhuron frikë dhe respekt ndaj Allahut, ajo do të jetë vetëm një barrë dhe dëshmi kundër teje në Ditën e Gjykimit.', 'Ibn Ata\'ilah'),
    DailyQuote('Edukimi i fëmijëve është si shkrimi mbi gur; ajo që u mëson atyre në fëmijëri do të mbetet për gjithë jetën.', 'Imam El Gazali'),
    DailyQuote('Kush kërkon diturinë për hir të Allahut, Allahu do t\'i dhurojë sukses dhe dritë në çdo punë të tij.', 'Hasan el Basri'),
    DailyQuote('Njeriu më i mençur është ai që llogarit veten e tij përpara se të llogaritet nga të tjerët, dhe e përgatit veten për takimin me Allahun.', 'Ibn Kajjimi'),
    DailyQuote('Kush kërkon diturinë për hir të Allahut, zemra e tij do të ndriçohet dhe do të gjejë rrugën e drejtë.', 'Ibn Tejmijje'),
    DailyQuote('Iu ankova Uekiut për dobësinë e mbajtjes mend, dhe ai më këshilloi t\'i lë mëkatet. Më tha: "Dije se dituria është dritë, dhe drita e Allahut nuk i jepet një mëkatari."', 'Imam Shafiu'),
    DailyQuote('Njeriu më i mençur është ai që i shton veprat e mira dhe pakëson pretendimet e tij.', 'Sufjan eth-Theuri'),
    DailyQuote('Kush mbart dituri dhe nuk vepron sipas saj, është si i padituri që endet në errësirë; argumenti i Zotit kundër tij është edhe më i madh.', 'Ali ibn Abi Talib'),
    DailyQuote('Nuk mund të arrihet dituria e saktë pa pasur një mësues udhëzues, sepse librat pa shpjegim shpesh mund të keqkuptohen.', 'Imam Ebu Hanife'),
    DailyQuote('I ditur është ai që e njeh vlerën e vet dhe nuk i tejkalon kufijtë e tij; injoranca më e madhe është kur njeriu nuk njeh veten e vet.', 'Ali ibn Abi Talib'),
    DailyQuote('Bëj durim ndaj ashpërsisë së mësuesit tënd, sepse dështimi në dituri qëndron në largimin prej tij. Kushdo që nuk e shijon hidhërimin e të mësuarit për një çast, do të gëlltisë poshtërimin e paditurisë gjatë gjithë jetës.', 'Imam Shafiu'),
    DailyQuote('Thjeshtësia dhe përulësia janë stolitë më të bukura të dijetarit; sa më shumë që shtohet dija, aq më shumë shtohet përulësia.', 'Imam Ebu Hanife'),
    DailyQuote('Frika nga Zoti është çelësi që hap dyert e kuptueshmërisë së saktë të fesë dhe urtësisë.', 'Imam Maliku'),
    DailyQuote('Askush nuk e kërkon diturinë me kryelartësi dhe mendjemadhësi e të ketë sukses. Ai që e kërkon atë me thjeshtësi dhe përulësi, duke u shërbyer dijetarëve, do të ketë sukses.', 'Imam Shafiu'),
    DailyQuote('Nuk është turp që një dijetar të thotë "nuk e di" për një çështje që nuk e ka studiuar mirë; ky është tregues i devotshmërisë së tij.', 'Imam Ebu Hanife'),
    DailyQuote('Kush tregohet mendjemadh me diturinë e tij, Allahu do ta zhveshë nga autoriteti dhe do ta poshtërojë.', 'Sufjan eth-Theuri'),
    DailyQuote('Udhëtimi larg atdheut për të kërkuar lartësi ka pesë dobi: largimin e brengave, fitimin e jetesës, përfitimin e diturisë, mësimin e sjelljes dhe shoqërimin me njerëz fisnikë.', 'Imam Shafiu'),
    DailyQuote('Dija kërkohet duke shkuar tek ajo, ajo nuk vjen vetë tek ti.', 'Imam Maliku'),
    DailyQuote('Grindja dhe debati i kotë për çështjet e dijes e largojnë dritën e saj nga zemra e robit.', 'Imam Maliku'),
    DailyQuote('Robi nuk i afrohet Allahut me ndonjë gjë më të mirë sansa mendimi i mirë për njerëzit dhe fshehja e veprave të mira.', 'Imam Maliku'),
    DailyQuote('Kur njeriu plaket, ai duhet të shtojë përpjekjet dhe dëshirën e tij për dije dhe për vepra të mira.', 'Imam Maliku'),
    DailyQuote('Nuk ka nder më të madh sansa dija e vërtetë, dhe nuk ka turp më të madh sansa injoranca e fshehur pas mburrjes.', 'Fudejl ibn Ijad'),
    DailyQuote('Kush nuk e shpenzon rininë e tij në kërkim të dijes, do të pendohet shumë kur të plaket.', 'Ibn Xhewzi'),
    DailyQuote('Mos u shoqëro me të paditurin, sepse duke dashur të të bëjë mirë, ai të dëmton; dhe mos u shoqëro me koprracin, sepse ai largohet prej teje kur ti ke më së shumti nevojë.', 'Ali ibn Abi Talib'),
    DailyQuote('Nuk kam dhënë asnjë fetva derisa shtatëdhjetë dijetarë të njohur dëshmuan se unë jam i aftë për këtë.', 'Imam Maliku'),
    DailyQuote('Dituria e vërtetë është ajo që ndikon pozitivisht në sjelljen tënde me familjen dhe njerëzit që të rrethojnë, e jo thjesht grumbullimi i informacioneve.', 'Imam Ebu Hanife'),
    DailyQuote('Dija nuk është me të pasurit shumë transmetime, por dija është një dritë që Allahu e vendos në zemër.', 'Imam Maliku'),
  ];
}
